### ISSUE TITLE
mu-plugin problem between GitHub and wp.org

### ISSUE THREAD

**Issue by afragen** [dannyvankooten/wp-plugin-profiler#11]
There's an issue whether or not the plugin is installed or updated between the 2 sources. This comes about because the repository name is not the same.

Users who download from GitHub will have a plugin source directory of `wp-plugin-profiler` and users from wp.org will have `plugin-profiler`.

It would be best to keep to one or the other as both may (and has here) cause fatal PHP errors where the mu-plugin is looking in the wrong directory for the plugin.

**Comment by tnorthcutt** [comment]
+1, just ran into this. Easy enough to sort out, but consistency would be welcome.

**Comment by dannyvankooten** [comment]
Hi all,

I tend to prefix my WordPress related repository's with `wp-` but didn't think it would make sense to use the same prefix for the actual WordPress.org repository (since it's obviously a WP plugin if it's on there).

Here's my current idea for tackling this one.

1) Adding a UI to automatically create the `mu-plugin` file and grabbing the plugin directory name dynamically (see #2).

2) Add clone instructions to GitHub README explicitly telling people to clone the repository into a directory named `plugin-profiler`.

`
git clone git@github.com:dannyvankooten/wp-plugin-profiler.git plugin-profiler
`

I think this will eliminate the naming inconsistency for most users. Let me know if you have any other suggestions. :smile:

**Comment by afragen** [comment]
Any update via GitHub Updater will automatically rename the directory.

Since the plugin is on WP.org as long as the version numbers in .org and GitHub are the same, the updates will pull from .org. 

In general though it's best to use the same structure.

**Comment by dannyvankooten** [comment]
@afragen Hm, I can see that being a problem. Isn't there a way to specify the directory for GitHub Updater to use? The GitHub URI is parsed from the `readme.txt` file, correct? Wouldn't it be an idea to use the plugin directory that is used? Many plugins allow renaming its plugin directory, for various reasons (symlinked plugins, etc.).

**Comment by afragen** [comment]
@dannyvankooten there is no way to specify a directory using GitHub Updater. It takes the directory name from the repo name. The `GitHub Plugin URI` in the plugin's header is what's parsed.

Just like how wp.org requires the slug to be the same as the plugin file and the plugin's directory to simplify updating it makes sense for the same plugin, even though hosted in different locations to be using the same directory structure.

I understand if you want to use a different structure in GitHub for your wp plugins but if those plugins are also hosted on wp.org this will persist. It may be easier to try and ensure users download the plugin from wp.org and not from GitHub.

**Comment by afragen** [comment]
> @afragen Hm, I can see that being a problem. Isn't there a way to specify the directory for GitHub Updater to use? The GitHub URI is parsed from the readme.txt file, correct? Wouldn't it be an idea to use the plugin directory that is used? Many plugins allow renaming its plugin directory, for various reasons (symlinked plugins, etc.).

There's a new branch `long-rename2` in GitHub Updater that will rename the directory in an extended format like `github-dannyvankooten-wp-plugin-profiler`. Perhaps it's relevant. https://github.com/afragen/github-updater/issues/239
